# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Properties-YAML
version:      0.01
version_from: lib/Data/Properties/YAML.pm
installdirs:  site
requires:
    YAML:                          

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
